### PR TITLE
Allow customizing Table column header background/foreground

### LINKED ISSUE #409: Add background and foreground config to Table Header

### PR DESCRIPTION
**Pull request by gabro**
Closes #409

### CODE REVIEW

**Review by veej — APPROVED** [review]
🥑

**Review by marcopiii — APPROVED** [review]
🍍

**Comment by gabro** [comment]
@Phyele as discussed yesterday, here's the attempt at making the sort icon currentColor + 80% opacity:

image

image

**Comment by gabro** [comment]
@Phyele merging as is to unblock the release, we can come back to this on Monday and potentially improve it

**Pull request merged**
