### PR TITLE
Review of #190 

### PR DESCRIPTION
**Pull request by gabro**
@veej an alternative to the solution proposed in #190

### CODE REVIEW

**Review by veej — APPROVED** [review]
💯

**Review by veej — CHANGES_REQUESTED** [review]
@gabro looking at the screenshot, I think there's something wrong in the chip height... 
This is my solution:
image

And here how it appears with yours:
image

**Comment by veej** [comment]
🤔 I tried to open it in storybook and I see this:
image

**Comment by gabro** [comment]
woops, fixed now

**Review by veej — APPROVED** [review]
Looks great 💯

**Pull request merged**
